# Generated by Django 5.0.6 on 2026-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("phone_screen", "Phone screen"),
                            ("interview", "Interview"),
                            ("take_home", "Take-home"),
                            ("onsite", "Onsite"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("ghosted", "Ghosted"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_local", models.BooleanField(default=False)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fit",
                    models.CharField(
                        choices=[
                            ("strong", "Strong fit"),
                            ("good", "Good fit"),
                            ("stretch", "Stretch"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("angle", models.CharField(blank=True, max_length=200)),
                ("contact", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("followup_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-applied_date", "company"],
            },
        ),
        migrations.CreateModel(
            name="JobLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("salary_text", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="One-line why-it-fits from the scout."
                    ),
                ),
                ("is_local", models.BooleanField(default=False)),
                ("discovered_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("applied", "Applied"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="joblead",
            constraint=models.UniqueConstraint(
                fields=("company", "title", "url"), name="uniq_lead"
            ),
        ),
    ]
