# Generated by Django 5.0.6 on 2026-08-31 14:56

import applications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_tasktoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan for jobs'), ('enrich', 'Enrich a link'), ('tailor', 'Tailor resume for a lead')], max_length=10),
        ),
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docx', models.FileField(upload_to=applications.models.tailored_resume_upload_path)),
                ('job_url', models.URLField(blank=True, max_length=1000)),
                ('keywords', models.TextField(blank=True, help_text='Job-posting keywords the tailoring worked in, one per line.')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resume', to='applications.joblead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
