# Generated by Django 5.0.6 on 2026-08-31 15:11

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_agenttask_kind_tailoredresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.application_resume_upload_path),
        ),
    ]
